checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*
  paths:
    - src/

build:
  environment:
    php:
      version: 7.2
  dependencies:
    override:
      -
        command: 'composer require --dev "symfony/browser-kit:4.4.*" "symfony/framework-bundle:4.4.*" "symfony/css-selector:4.4.*" "symfony/form:4.4.*" "symfony/http-kernel:4.4.*" "symfony/phpunit-bridge:4.4.*" "symfony/security-bundle:4.4.*" "symfony/twig-bundle:4.4.*" "symfony/validator:4.4.*" "symfony/yaml:4.4.*" --no-update'
      -
        command: 'composer update --no-interaction -vv --profile --no-progress'
        idle_timeout: 900
  tests:
    override:
      -
        command: 'php ./vendor/bin/phpunit --coverage-clover=coverage-clover'
        idle_timeout: 300
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
